[build]
  command = "yarn build"
  publish = "build"
  GENERATE_SOURCEMAP = "true"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"